import { router, useLocalSearchParams } from "expo-router";
import { Check, ChevronRight, Gift, Heart, TicketPercent } from "lucide-react-native";
import React, { useState } from "react";
import { Image, Pressable, StyleSheet, Text, View } from "react-native";
import { AccessiblePressable, AppHeader, Empty, Screen } from "@/components/ui";
import { deals } from "@/lib/data";
import { useStore } from "@/lib/store";
import { F,shadow,type ThemeColors,useAppTheme } from "@/lib/theme";
const offerNames=(deal:any)=>[deal.offer,"Complimentary dessert with two mains","20% off your total bill"];
export default function SavedScreen(){const {colors:C}=useAppTheme();const s=React.useMemo(()=>makeStyles(C),[C]);const params=useLocalSearchParams<{segment?:string}>();const requested=params.segment;const initialSegment=requested==="Offers"||requested==="Used"?requested:"Places";const [segment,setSegment]=useState<"Places"|"Offers"|"Used">(initialSegment);const {state,toggleSaved,notify}=useStore();const savedDeals=deals.filter(d=>state.saved.includes(d.id));const usedDeals=deals.filter(d=>state.used.includes(d.id));return <Screen testID="saved-screen"><AppHeader eyebrow="YOUR COLLECTION" title="Saved for later" right={<Text accessibilityLabel={`${state.saved.length+state.savedOffers.length} saved items`} style={s.count}>{state.saved.length+state.savedOffers.length}</Text>}/><Text style={s.intro}>All your good ideas, in one place.</Text><View accessibilityRole="tablist" style={s.segments}>{(["Places","Offers","Used"] as const).map(x=><AccessiblePressable accessibilityRole="tab" accessibilityState={{selected:segment===x}} haptic="selection" testID={`saved-${x}`} key={x} onPress={()=>setSegment(x)} style={[s.segment,segment===x&&s.active]}><Text style={[s.text,segment===x&&s.activeText]}>{x}</Text></AccessiblePressable>)}</View>
 {segment==="Places"&&(savedDeals.length?savedDeals.map(d=><View style={s.placeCard} key={d.id}><Pressable onPress={()=>router.push(`/deal/${d.id}`)} style={s.placeMain}><Image source={{uri:d.image}} style={s.image}/><View style={{flex:1}}><Text style={s.meta}>{d.category.toUpperCase()} · {d.distance}</Text><Text style={s.title}>{d.name}</Text><Text style={s.offer} numberOfLines={1}>{d.offer}</Text><Text style={s.saving}>{d.saving}</Text></View></Pressable><Pressable accessibilityLabel={`Remove ${d.name} from saved`} onPress={()=>toggleSaved(d.id)} style={s.heart}><Heart size={18} fill={C.lime}/></Pressable></View>):<Empty title="Nothing here yet" body="Tap the heart on an offer you love and it will wait for you here."/>)}
 {segment==="Offers"&&(state.savedOffers.length?<View>{state.savedOffers.map(key=>{const [dealId,index]=key.split("-").map(Number);const d=deals.find(x=>x.id===dealId);if(!d)return null;return <Pressable key={key} onPress={()=>router.push(`/deal/${d.id}`)} style={s.offerRow}><View style={s.offerIcon}><TicketPercent size={20}/></View><View style={{flex:1}}><Text style={s.meta}>{d.name.toUpperCase()}</Text><Text style={s.title}>{offerNames(d)[index]}</Text><Text style={s.saving}>{index===0?d.saving:`Save ₹${250+index*150}`}</Text></View><ChevronRight size={18}/></Pressable>})}</View>:<Empty title="No saved offers yet" body="Save an individual member price from any partner page."/>)}
 {segment==="Used"&&(usedDeals.length?usedDeals.map(d=><Pressable key={d.id} onPress={()=>router.push(`/deal/${d.id}`)} style={s.offerRow}><View style={[s.offerIcon,{backgroundColor:C.lime}]}><Check size={20}/></View><View style={{flex:1}}><Text style={s.meta}>REDEEMED</Text><Text style={s.title}>{d.name}</Text><Text style={s.offer}>{d.offer}</Text></View><ChevronRight size={18}/></Pressable>):<Empty icon="✓" title="No used offers yet" body="Redeemed discounts and booking codes will appear here."/>)}
 <Pressable onPress={()=>notify("Gift link created for your saved offers")} style={s.tip}><Gift size={22}/><View style={{flex:1}}><Text style={s.tipTitle}>Share the savings</Text><Text style={s.tipBody}>Gift a saved offer to someone you love.</Text></View><ChevronRight size={18}/></Pressable>
 </Screen>}
const makeStyles=(C:ThemeColors)=>StyleSheet.create({count:{width:44,height:44,borderRadius:15,backgroundColor:C.lime,color:C.ink,textAlign:"center",textAlignVertical:"center",fontFamily:F.bodyBold},intro:{fontFamily:F.body,fontSize:13,color:C.muted,marginTop:-11,marginBottom:15},segments:{minHeight:52,borderRadius:17,backgroundColor:C.soft,padding:4,flexDirection:"row",marginBottom:14},segment:{flex:1,borderRadius:13,alignItems:"center",justifyContent:"center"},active:{backgroundColor:C.card,...shadow},text:{fontFamily:F.bodyBold,fontSize:13,color:C.muted},activeText:{color:C.ink},placeCard:{minHeight:124,borderRadius:21,backgroundColor:C.card,padding:10,marginBottom:10,borderWidth:1,borderColor:C.line,...shadow},placeMain:{flexDirection:"row",alignItems:"center",gap:11,paddingRight:44},image:{width:92,height:100,borderRadius:16},meta:{fontFamily:F.bodyBold,fontSize:11,color:C.ink,letterSpacing:.7},title:{fontFamily:F.headingSemi,fontSize:17,color:C.ink,marginVertical:4},offer:{fontFamily:F.body,fontSize:12,color:C.muted},saving:{fontFamily:F.bodyBold,fontSize:12,color:C.ink,marginTop:5},heart:{position:"absolute",right:8,top:8,width:44,height:44,borderRadius:14,backgroundColor:C.ink,alignItems:"center",justifyContent:"center"},offerRow:{minHeight:108,borderRadius:20,backgroundColor:C.card,padding:12,flexDirection:"row",alignItems:"center",gap:11,marginBottom:9,borderWidth:1,borderColor:C.line,...shadow},offerIcon:{width:48,height:48,borderRadius:15,backgroundColor:C.soft,alignItems:"center",justifyContent:"center"},tip:{minHeight:94,borderRadius:20,backgroundColor:C.lime,padding:15,flexDirection:"row",alignItems:"center",gap:12,marginTop:12},tipTitle:{fontFamily:F.headingSemi,fontSize:17,color:C.ink},tipBody:{fontFamily:F.body,fontSize:12,color:C.ink,marginTop:3}});
