import * as Linking from "expo-linking";
import { router, useLocalSearchParams } from "expo-router";
import { BriefcaseBusiness, Check, MapPin, Share2 } from "lucide-react-native";
import React, { useState } from "react";
import { Image, Pressable, Share, StyleSheet, Text, View } from "react-native";
import { AccessiblePressable, AppHeader, Empty, PrimaryButton, Screen } from "@/components/ui";
import { RedemptionSheet } from "@/components/RedemptionSheet";
import { listingById, onlineUrlFor } from "@/lib/data";
import { F,shadow,type ThemeColors,useAppTheme } from "@/lib/theme";
export default function ListingDetail(){const {colors:C}=useAppTheme();const s=React.useMemo(()=>makeStyles(C),[C]);const {id}=useLocalSearchParams<{id:string}>();const item=listingById(id);const [redeem,setRedeem]=useState(false);const [complete,setComplete]=useState(false);if(!item)return <Screen><AppHeader title="Listing" back/><Empty icon="?" title="Listing not found" body="Try browsing the latest Kouponly results."/></Screen>;const redemptionMode=item.redemption??(item.type==="Experience"?"online":undefined);const partnerUrl=redemptionMode==="online"?onlineUrlFor(item.title,item.externalUrl):item.externalUrl;const act=()=>{if(item.dealId)return router.replace(`/deal/${item.dealId}`);if(item.destination==="work")return router.push("/work");if(item.destination==="rewards")return router.push("/rewards");if(redemptionMode)return setRedeem(true);if(item.externalUrl)return Linking.openURL(item.externalUrl);setComplete(true)};return <><Screen testID="listing-detail"><AppHeader eyebrow={item.type.toUpperCase()} title="Kouponly pick" back right={<AccessiblePressable accessibilityLabel="Share listing" onPress={()=>Share.share({message:`${item.title} on Kouponly`})} style={s.share}><Share2 color={C.ink} size={19}/></AccessiblePressable>}/><Image accessible={false} source={{uri:item.image}} style={s.image}/><View style={s.tag}><Text style={s.tagText}>{item.tag}</Text></View><Text accessibilityRole="header" style={s.title}>{item.title}</Text><View style={s.meta}><MapPin color={C.ink} size={16}/><Text style={s.metaText}>{item.subtitle}</Text></View><Text style={s.description}>{item.description}</Text><View style={s.factGrid}><View style={{flex:1}}><Text style={s.factLabel}>TYPE</Text><Text style={s.fact}>{item.type}</Text></View><View style={{flex:1}}><Text style={s.factLabel}>DISTANCE</Text><Text style={s.fact}>{item.distance?`${item.distance} km`:"Online"}</Text></View></View><View style={s.brief}><BriefcaseBusiness color={C.ink} size={24}/><View style={{flex:1}}><Text style={s.briefTitle}>What happens next</Text><Text style={s.description}>Review the details, continue with the partner or complete the local prototype action.</Text></View></View>{complete?<View accessibilityRole="alert" style={s.success}><Check color={C.inkOnAccent} size={24}/><Text style={s.successText}>Interest recorded</Text></View>:<PrimaryButton testID="listing-action" label={item.action} onPress={act}/>}</Screen><RedemptionSheet visible={redeem} id={`listing-${item.id}`} title={item.title} mode={redemptionMode??"inStore"} externalUrl={partnerUrl} onClose={()=>setRedeem(false)}/></>}
const makeStyles=(C:ThemeColors)=>StyleSheet.create({share:{width:44,height:44,borderRadius:15,backgroundColor:C.soft},image:{width:"100%",height:260,borderRadius:27},tag:{alignSelf:"flex-start",backgroundColor:C.lime,borderRadius:12,paddingHorizontal:10,paddingVertical:8,marginTop:-17,marginLeft:14},tagText:{fontFamily:F.bodyBold,fontSize:12,color:C.inkOnAccent},title:{fontFamily:F.heading,fontSize:30,color:C.ink,letterSpacing:-1,marginTop:16},meta:{flexDirection:"row",gap:6,alignItems:"center",marginTop:8},metaText:{fontFamily:F.body,fontSize:14,color:C.ink},description:{fontFamily:F.body,fontSize:14,lineHeight:21,color:C.muted,marginTop:10},factGrid:{flexDirection:"row",gap:16,marginVertical:20},factLabel:{fontFamily:F.bodyBold,fontSize:11,letterSpacing:1,color:C.muted},fact:{fontFamily:F.headingSemi,fontSize:17,color:C.ink,marginTop:5},brief:{minHeight:118,borderRadius:22,backgroundColor:C.soft,padding:15,flexDirection:"row",gap:12,marginBottom:20},briefTitle:{fontFamily:F.headingSemi,fontSize:17,color:C.ink},success:{minHeight:58,borderRadius:18,backgroundColor:C.lime,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:9,...shadow},successText:{fontFamily:F.headingSemi,fontSize:16,color:C.inkOnAccent}});
