create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  email text not null default '',
  city text not null default 'Kochi, Kerala',
  points integer not null default 680 check (points >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.saved_deals (user_id uuid references auth.users(id) on delete cascade, deal_id integer not null, created_at timestamptz not null default now(), primary key (user_id, deal_id));
create table public.saved_offers (user_id uuid references auth.users(id) on delete cascade, offer_id text not null, created_at timestamptz not null default now(), primary key (user_id, offer_id));
create table public.used_deals (user_id uuid references auth.users(id) on delete cascade, deal_id integer not null, used_at timestamptz not null default now(), primary key (user_id, deal_id));
create table public.offer_usage (user_id uuid references auth.users(id) on delete cascade, offer_id text not null, use_count integer not null default 0 check (use_count between 0 and 3), updated_at timestamptz not null default now(), primary key (user_id, offer_id));
create table public.campaign_applications (user_id uuid references auth.users(id) on delete cascade, campaign_id text not null, status text not null default 'submitted' check (status in ('submitted','withdrawn','approved','rejected')), note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key (user_id, campaign_id));
create table public.user_interests (user_id uuid references auth.users(id) on delete cascade, interest_id text not null, note text, created_at timestamptz not null default now(), primary key (user_id, interest_id));
create table public.redemptions (user_id uuid references auth.users(id) on delete cascade, redemption_id text not null, mode text not null check (mode in ('online','inStore')), status text not null check (status in ('warning','pin','code','success','expired')), code text, expires_at timestamptz, completed_at timestamptz, consumed_at timestamptz, updated_at timestamptz not null default now(), primary key (user_id, redemption_id));
create table public.redeemed_rewards (user_id uuid references auth.users(id) on delete cascade, reward_id text not null, redeemed_at timestamptz not null default now(), primary key (user_id, reward_id));
create table public.accepted_gifts (user_id uuid references auth.users(id) on delete cascade, gift_id text not null, accepted_at timestamptz not null default now(), primary key (user_id, gift_id));
create table public.sent_gifts (id bigint generated by default as identity primary key, user_id uuid references auth.users(id) on delete cascade, offer text not null, recipient text not null, sent_at timestamptz not null default now());
create table public.feedback (id bigint generated by default as identity primary key, user_id uuid references auth.users(id) on delete set null, message text not null check (char_length(message) between 5 and 4000), created_at timestamptz not null default now());

create index sent_gifts_user_id_idx on public.sent_gifts (user_id, sent_at desc);
create index feedback_user_id_idx on public.feedback (user_id, created_at desc);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (user_id, full_name, email)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', ''), coalesce(new.email, ''))
  on conflict (user_id) do nothing;
  return new;
end;
$$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

do $$
declare table_name text;
begin
  foreach table_name in array array['profiles','saved_deals','saved_offers','used_deals','offer_usage','campaign_applications','user_interests','redemptions','redeemed_rewards','accepted_gifts','sent_gifts','feedback'] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('create policy "Users manage their own %1$s" on public.%1$I for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id)', table_name);
    execute format('grant select, insert, update, delete on public.%I to authenticated', table_name);
  end loop;
end $$;
grant usage, select on all sequences in schema public to authenticated;

create or replace function public.sync_user_state(p_state jsonb) returns void language plpgsql security invoker set search_path = '' as $$
declare uid uuid := (select auth.uid());
begin
  if uid is null then raise exception 'Authentication required'; end if;
  insert into public.profiles (user_id, points) values (uid, greatest(0, coalesce((p_state->>'points')::integer, 680)))
  on conflict (user_id) do update set points = excluded.points, updated_at = now();

  delete from public.saved_deals where user_id = uid;
  insert into public.saved_deals (user_id, deal_id) select uid, value::integer from jsonb_array_elements_text(coalesce(p_state->'saved','[]'::jsonb));
  delete from public.saved_offers where user_id = uid;
  insert into public.saved_offers (user_id, offer_id) select uid, value from jsonb_array_elements_text(coalesce(p_state->'savedOffers','[]'::jsonb));
  delete from public.used_deals where user_id = uid;
  insert into public.used_deals (user_id, deal_id) select uid, value::integer from jsonb_array_elements_text(coalesce(p_state->'used','[]'::jsonb));
  delete from public.offer_usage where user_id = uid;
  insert into public.offer_usage (user_id, offer_id, use_count) select uid, key, least(3, greatest(0, value::integer)) from jsonb_each_text(coalesce(p_state->'offerUsage','{}'::jsonb));
  delete from public.campaign_applications where user_id = uid;
  insert into public.campaign_applications (user_id, campaign_id) select uid, value from jsonb_array_elements_text(coalesce(p_state->'appliedCampaigns','[]'::jsonb));
  delete from public.user_interests where user_id = uid;
  insert into public.user_interests (user_id, interest_id) select uid, value from jsonb_array_elements_text(coalesce(p_state->'interests','[]'::jsonb));
  delete from public.redemptions where user_id = uid;
  insert into public.redemptions (user_id, redemption_id, mode, status, code, expires_at, completed_at, consumed_at)
  select uid, key, value->>'mode', value->>'status', value->>'code', to_timestamp(nullif(value->>'expiresAt','')::double precision / 1000), to_timestamp(nullif(value->>'completedAt','')::double precision / 1000), to_timestamp(nullif(value->>'consumedAt','')::double precision / 1000)
  from jsonb_each(coalesce(p_state->'redemptions','{}'::jsonb));
  delete from public.redeemed_rewards where user_id = uid;
  insert into public.redeemed_rewards (user_id, reward_id) select uid, value from jsonb_array_elements_text(coalesce(p_state->'redeemedRewards','[]'::jsonb));
  delete from public.accepted_gifts where user_id = uid;
  insert into public.accepted_gifts (user_id, gift_id) select uid, value from jsonb_array_elements_text(coalesce(p_state->'acceptedGifts','[]'::jsonb));
  delete from public.sent_gifts where user_id = uid;
  insert into public.sent_gifts (user_id, offer, recipient, sent_at)
  select uid, value->>'offer', value->>'recipient', to_timestamp((value->>'sentAt')::double precision / 1000) from jsonb_array_elements(coalesce(p_state->'sentGifts','[]'::jsonb));
end;
$$;
grant execute on function public.sync_user_state(jsonb) to authenticated;
revoke execute on function public.sync_user_state(jsonb) from anon, public;
